# Generated by Django 2.2.13 on 2020-09-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='stars',
            field=models.CharField(max_length=5),
        ),
    ]
